controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ackermann_steering_controller:
  ros__parameters:
    rear_wheel_names:
      - left_rear_wheel_joint
      - right_rear_wheel_joint
    steering_joint_names:
      - left_steering_hinge_joint
      - right_steering_hinge_joint
    wheel_base: 0.325
    wheel_track: 0.2
    wheel_radius: 0.05
    open_loop: true
    publish_rate: 50
    velocity_rolling_window_size: 10
    cmd_ackermann_topic: /drive
    odom_topic: /odom
